version: '3'

services:
  strapi:
    container_name: strapi
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    environment:
      - PORT=1337
      - ADMIN_JWT_SECRET=fdc557d845496da740a345a1e5dfc04e
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
    ports:
      - 1337:1337
    volumes:
      - ./app:/strapi
      - hoge:/strapi/node_modules
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always

  webhook:
    container_name: webhook
    build:
      context: ../dreamer-strapi-webhook
      dockerfile: Dockerfile.dev
    env_file:
     - .env
    ports:
      - ${PORT}:${PORT}

volumes:
  hoge: