apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo-service
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-pod