kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: strapi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-deployment
  labels:
    app: strapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strapi-pod
  template:
    metadata:
      labels:
        app: strapi-pod
    spec:
      containers:
      - name: strapi-container
        image: tim0401/dreamer-strapi:0.3
        ports:
        - containerPort: 1337
        env:
        - name: PORT
          value: "1337"
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret
              key: admin-jwt-secret
        - name: DATABASE_HOST
          value: "mongo-sts-0.mongo-svc.default.svc.cluster.local:27017,mongo-sts-1.mongo-svc.default.svc.cluster.local:27017,mongo-sts-2.mongo-svc.default.svc.cluster.local:27017/?replicaSet=rs0"
        - name: DATABASE_PORT
          value: "27017"
        - name: DATABASE_NAME
          value: "dreamer-strapi"
        volumeMounts:
        - name: strapi-data
          mountPath: "/dreamer-strapi/app/public/uploads"

      - name: strapi-webhook-container
        image: tim0401/dreamer-strapi-webhook:latest
        env:
        - name: PORT
          value: "1338"     
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: secret
              key: webhook-url
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret
              key: github-token

      volumes:
      - name: strapi-data
        persistentVolumeClaim:
          claimName: strapi-pvc
